version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: andrei-oksentyk:master    # Required. Must be in the same fork network.
    mergeMethod: rebase  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: master
    upstream: elzan2000:master        # Required. Can be a branch in the same forked repo.